### ISSUE TITLE
:require/:use in ns decl makes cljs-watch fail

### ISSUE THREAD

**Issue by swannodette** [ibdknox/cljs-watch#3]
If I have a file that looks like:

``` clojure
(ns test.a
  (:use [test.b :only [bar]]))

(defn foo [a b]
  (bar a b))

(defn baz [c d]
  (* c d))
```

And a file that looks like this:

``` clojure
(ns test.b)

(defn bar [a b]
  (- a b))
```

I get the following error:

``` sh
27 Aug 30, 2011 7:57:19 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
28 WARNING: 1 error(s), 0 warning(s)
29 ERROR: JSC_DUPLICATE_INPUT. Duplicate input: .../test/resources/cljs/test/b.js at (unknown source) line (unknown line) : (unknown column)
30      [done]
```

**Comment by scottjad** [comment]
:use :only statements involving pinot work for me, but my own namespace didn't.

:: watcher :: Compiling updated files...WARNING: Use of undeclared Var emailatask.cljs.frontend/bar

(ns emailatask.cljs.frontend
  ;; (:refer-macros [emailatask.cljsmacros :as macros])
  (:use [emailatask.cljs.whatever :only (bar)])
  (:use [pinot.html :only (html dom-find text css val append-to)]
        [pinot.events :only (on prevent)]
        [pinot.remotes :only (remote-callback)])

**Comment by ibdknox** [comment]
I'm closing this for now per our discussion on IRC, feel free to reopen if you run into it again :)

**Comment by jedahu** [comment]
What was the resolution from the IRC chat? I am having the same problem.

**Comment by ibdknox** [comment]
Try what I just pushed :)

**Comment by jedahu** [comment]
Excellent!
